### ISSUE TITLE
Rename `scion-as` to something more suitable

### ISSUE THREAD

**Issue by martenwallewein** [netsys-lab/scion-as#1]
Potential candidates:
- scion-manager
- scion-supervisor
- scion-host-manager
- scion-node-supervisor

**Comment by hausheer** [comment]
How about scion-orchestrator

**Comment by martenwallewein** [comment]
Sounds good to me! In case there are no objections, I will do the renaming in the next days

**Comment by martenwallewein** [comment]
Done, repo is now under: https://github.com/netsys-lab/scion-orchestrator
